Update bashes default

diff --git a/shared/default/bash/aliases-base b/shared/default/bash/aliases-base
--- a/shared/default/bash/aliases-base
+++ b/shared/default/bash/aliases-base
@@ -3,21 +3,29 @@ alias system-update="sudo apt update && sudo apt -y upgrade && sudo apt -y dist-
 alias firmware-update="sudo fwupdmgr get-devices && sudo fwupdmgr get-updates && sudo fwupdmgr update"
 
 # File system
-alias ls='eza -lh --group-directories-first --icons=auto'
-alias lsa='ls -a'
-alias lt='eza --tree --level=2 --long --icons --git'
-alias lta='lt -a'
+if command -v eza &> /dev/null; then
+  alias ls='eza -lh --group-directories-first --icons=auto'
+  alias lsa='ls -a'
+  alias lt='eza --tree --level=2 --long --icons --git'
+  alias lta='lt -a'
+fi
+
+alias fd='fdfind'
 alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
-alias cd="zd"
-zd() {
-  if [ $# -eq 0 ]; then
-    builtin cd ~ && return
-  elif [ -d "$1" ]; then
-    builtin cd "$1"
-  else
-    z "$@" && printf " \U000F17A9 " && pwd || echo "Error: Directory not found"
-  fi
-}
+alias eff='$EDITOR "$(ff)"'
+
+if command -v zoxide &> /dev/null; then
+  alias cd="zd"
+  zd() {
+    if [ $# -eq 0 ]; then
+      builtin cd ~ && return
+    elif [ -d "$1" ]; then
+      builtin cd "$1"
+    else
+      z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
+    fi
+  }
+fi
 
 # Directories
 alias ..='cd ..'
@@ -25,9 +33,8 @@ alias ...='cd ../..'
 alias ....='cd ../../..'
 
 # Tools
-alias g='git'
 alias d='docker'
-n() { if [ "$#" -eq 0 ]; then nvim .; else nvim "$@"; fi; }
+n() { if [ "$#" -eq 0 ]; then command nvim . ; else command nvim "$@"; fi; }
 
 # Browser
 open() (
@@ -35,6 +42,7 @@ open() (
 )
 
 # Git
+alias g='git'
 alias gcm='git commit -m'
 alias gcam='git commit -a -m'
 alias gcad='git commit -a --amend'
